#!/usr/bin/env python3
import sys
import string

commit_msg_filepath = sys.argv[1]


def has_only_latin_letters(name):
	for leter in name:
		if leter not in string.printable:
			return True
	return False


with open(commit_msg_filepath, 'r') as f:
	comment = f.readline()
	if len(comment) < 10:
		print('Comment length must be at least 10')
		sys.exit(1)
	if len(comment.split()) < 2:
		print('Comment must contain at least 2 words')
		sys.exit(1)
	if has_only_latin_letters(comment):
		print('Only english in comments')
		sys.exit(1)
