#!/usr/bin/env python3
import sys
import subprocess

bashCommand = 'git branch'
process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
output, error = process.communicate()
branch_name = output[2:-1]

if branch_name == b'master':
	print("Can't push to master branch")
	sys.exit(1)
